# Generated by Django 3.2.6 on 2024-10-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='vr_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
