# Generated by Django 3.2.6 on 2024-10-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20241012_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='request_type',
            field=models.CharField(max_length=50),
        ),
    ]
