# Generated by Django 3.2.6 on 2024-10-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20241012_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='request_type',
            field=models.CharField(max_length=100),
        ),
    ]
