# Generated by Django 3.2.6 on 2024-10-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_maintenancerequest_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='request_type',
            field=models.CharField(max_length=50),
        ),
    ]
