# Generated by Django 3.2.6 on 2025-02-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_maintenancerequest_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], default='sale', max_length=10),
        ),
    ]
