# Generated by Django 3.2.6 on 2025-02-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listing_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='rent_payment_schedule',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('weekly', 'Weekly'), ('daily', 'Daily'), ('any', 'Any')], max_length=10, null=True),
        ),
    ]
