# Generated by Django 3.2.6 on 2025-02-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listing_rent_payment_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_furnished',
            field=models.BooleanField(default=False, verbose_name='هل العقار مكسي؟'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_labels',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='تصنيفات الصور'),
        ),
    ]
