# Generated by Django 3.2.6 on 2025-02-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20250211_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%m'),
        ),
    ]
