# Generated by Django 3.2.6 on 2025-02-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_listing_photo_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo_categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
