# Generated by Django 3.2.6 on 2025-02-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_listing_photo_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='photo_categories',
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_main_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
