# Generated by Django 3.2.6 on 2025-02-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_auto_20250212_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo_1_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_2_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_3_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_4_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_5_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
