# Generated by Django 3.2.6 on 2025-02-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_auto_20250212_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='google_maps_link',
            field=models.URLField(blank=True),
        ),
    ]
