# Generated by Django 3.2.6 on 2025-02-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_listing_google_maps_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='google_maps_link',
        ),
        migrations.AddField(
            model_name='listing',
            name='google_maps_embed_link',
            field=models.TextField(blank=True),
        ),
    ]
