# Generated by Django 3.2.6 on 2025-02-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_auto_20250212_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='vr_link',
        ),
        migrations.AddField(
            model_name='listing',
            name='vr_embed_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
