# Generated by Django 3.2.6 on 2025-02-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_savedlisting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='google_maps_embed_link',
        ),
        migrations.AddField(
            model_name='listing',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
