# Generated by Django 3.2.6 on 2025-02-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_auto_20250218_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='longitude',
        ),
        migrations.AddField(
            model_name='listing',
            name='google_maps_embed_link',
            field=models.TextField(blank=True),
        ),
    ]
