# Generated by Django 3.2.6 on 2025-02-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_auto_20250218_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='google_maps_embed_link',
            field=models.URLField(blank=True),
        ),
    ]
