# Generated by Django 5.1.6 on 2025-03-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_alter_listing_google_maps_embed_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='request_type',
            field=models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('heating', 'Heating'), ('cooling', 'Cooling'), ('general', 'General Maintenance')], max_length=50),
        ),
    ]
